config/routes.rb
Rails.application.routes.draw do

  resources :articles

  get 'welcome/index'
  root 'welcome#index'

  get 'profile' => 'profile#index'
  get 'profile/edit'
  put 'profile/edit'
  post 'profile' => 'profile#update'

  get 'login' => 'sessions#index'
  post 'login' => 'sessions#login'
  delete 'logout' => 'sessions#logout'

  get 'signup' => 'signup#index'
  post 'signup' => 'signup#signup'

end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base

  # normalize email
  after_validation :downcase_email

  def downcase_email
    self.email = email.downcase
  end

  # email must be present, be an email and be confirmed
  validates :email, presence: {message: 'must be present, please specify one.'}
  validates :email, email: true
  validates :email, confirmation: true

  # email must be unique
  validates :email, uniqueness: {message: 'already registered, please use another one.'}

  # password must be present
  validates :password, presence: {message: 'must be present, please specify one.'}

  # authenticate the user
  def authenticate (password)
    self.password == password
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  # redirect to login if not logged in
  def authorize
    redirect_to '/login' unless logged_in
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  # add authentication for all actions
  before_filter :authorize

  # show all articles
  def index
    @articles = Article.all
  end

  # get form page for creating
  def new
  end

  # post action to create a new article
  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to articles_path
    else
      render 'new'
    end
  end

  # show specific article
  def show
    @article = Article.find(params[:id]);
  end

  # get article for edit
  def edit
    @article = Article.find(params[:id])
  end

  # post action for editing article
  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to articles_path
    else
      render 'edit'
    end
  end

  # delete specific article
  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

  private

  # get article object from http params
  def article_params
    params.require(:article).permit(:title, :text)
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController

  # add authentication for all actions
  before_filter :authorize

  # show profile
  def index
    @profile = current_user
  end

  def edit
    @profile = current_user
  end

  # post action for editing article
  def update
    @profile = current_user

    if current_user.update(edit_params)
      redirect_to profile_path
    else
      render 'edit'
    end
  end

  def edit_params
    params.require(:user).permit(:name, :name, :address)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  # render login form
  def index
    if logged_in
      redirect_to articles_path
    end
    @user = User.new
  end

  # login user with credentials
  def login
    @user = User.find_by(email: params[:session][:email].downcase)

    if @user && @user.authenticate(params[:session][:password])
      # Log the user in and redirect to the article page
      log_in @user
      redirect_to articles_path
    else
      # show error message that user is invalid
      flash.now[:error] = 'Invalid username/password'
      render 'index'
    end
  end

  # logout
  def logout
    log_out
    redirect_to login_path
  end

end

app/controllers/signup_controller.rb
class SignupController < ApplicationController

  def index
  end

  def signup
    @user = User.new(user_params)
    if @user.save
      render 'confirm'
    else
      render 'index'
    end
  end
end

# get user object from http params
def user_params
  params.require(:user).permit(:email, :email_confirmation, :password, :name, :address)
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  #log in the user
  def log_in(user)
    session[:user_id] = user.id
  end

  #return the current logged in user
  def current_user
    if @current_user.nil?
      @current_user = User.find_by(id: session[:user_id])
    else
    @current_user
    end
  end

  #return true if user is logged in already
  def logged_in
    !current_user.nil?
  end

  #destroy the session and every detail about the user
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

end

app/helpers/signup_helper.rb
module SignupHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/edit.html.erb
<div class="container">
	<h3 class="page-header">Edit Article</h3>
	<% if @article && @article.errors.any? %>
	<div class="alert alert-danger">
		<% @article.errors.full_messages.each do |error| %>
		<span><%= error %></span>
		<% end %>
	</div>
	<% end %>
	<%= form_for :article, class:"form form-horizontal",  url:article_path(@article), method: :patch do |f| %>
	<div class="form-group">
		<%= f.label :title %>
		<br>
		<%= f.text_field :title, class:'form-control', value: @article.title %>
	</div>
	<div class="form-group">
		<%= f.label :text %>
		<br>
		<%= f.text_area :text, class:'form-control', value: @article.text %>
	</div>
	<div class="form-group">
		<%= f.submit "Save", class: "btn btn-primary" %>
	</div>
	<% end %>
	<p>
		<span>&laquo;</span><%= link_to "Back to Articles", articles_path %>
	</p>
</div>

app/views/articles/index.html.erb
<div class="container">
	<h3 class="page-header">Listing Articles</h3>

	<p>
		<%= link_to "New Article", new_article_path %>
	</p>
	<table class="table table-striped table-hover table-bordered">
		<tr>
			<th>Title</th>
			<th>Text</th>
			<th>Actions</th>
		</tr>
		<% @articles.each do |article| %>
		<tr>
			<td><%= article.title %></td>
			<td class="oneliner"><%= article.text %></td>
			<td>
			<div class="btn-group btn-group-sm">
				<%= link_to "View", article_path(article.id), class: "btn btn-default" %>
				<%= link_to "Edit", edit_article_path(article.id), class: "btn btn-primary" %>
				<%= link_to "Delete", article_path(article),
				method: :delete,
				data: { confirm: "Are you sure?"},
				class: "btn btn-danger" %>
			</div></td>
		</tr>
		<% end %>
	</table>
</div>

app/views/articles/new.html.erb
<div class="container">
	<h3 class="page-header">New Article</h3>

	<% if @article && @article.errors.any? %>
	<div class="alert alert-danger">
		<% @article.errors.full_messages.each do |error| %>
		<span><%= error %></span>
		<% end %>
	</div>
	<% end %>
	<%= form_for :article, class:"form form-horizontal",  url:articles_path do |f| %>
	<div class="form-group">
		<%= f.label :title %>
		<br>
		<%= f.text_field :title, placeholder: "Enter your title...",  class:'form-control' %>
	</div>
	<div class="form-group">
		<%= f.label :text %>
		<br>
		<%= f.text_area :text, placeholder: "Enter your text here", cols: '30', rows:'10', class:'form-control' %>
	</div>
	<div class="form-group">
		<%= f.submit "Save", class: 'btn btn-primary' %>
	</div>
	<% end %>
</div>

app/views/articles/show.html.erb
<div class="container">
	<h3 class="page-header">View Article</h3>
	<%= link_to "New Article", new_article_path %>
	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title"><%= @article.title %></h3>
		</div>
		<div class="panel-body">
			<p>
				<%= @article.text %>
			</p>
		</div>
	</div>
	<span>&laquo;</span><%= link_to "Back to Articles", articles_path %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-inverse navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" data-toggle="collapse" data-target="#navMenu" class="collapsed navbar-toggle">
        <span class="sr-only">Toggle Navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand"><%= link_to 'Blog', root_path, class: 'navbar-link' %></span>
    </div>
    <div class="collapse navbar-collapse" id="navMenu">
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in %>
            <li>
              <%= link_to 'Articles', articles_path %>
            </li>
            <li class="dropdown">
              <a href="#" data-toggle="dropdown" role="button" class="dropdown-toggle">
                <%= current_user.name || current_user.email %>
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li>
                  <%= link_to 'Profile', profile_path %>
                </li>
                <li>
                  <%= link_to 'Logout', logout_path, method: 'delete' %>
                </li>
              </ul>
            </li>
        <% else %>
            <% if login_path && !logged_in %>
                <li>
                  <%= link_to 'Login', login_path %>
                </li>
            <% end %>
            <li>
              <%= link_to 'Sign up', signup_path %>
            </li>
        <% end %>

      </ul>
    </div>
  </div>
</nav>

<%= yield %>

</body>
</html>

app/views/signup/confirm.html.erb
<div class="container">
  <h3 class="page-header">Signup confirmed</h3>

  <p>Please login with your email <%= @user.email %> and password</p>

  <p><%= link_to 'Login', login_path, class: 'btn btn-primary' %></p>
</div>

app/views/signup/index.html.erb
<div class="container">
  <h3 class="page-header">Sign up</h3>

  <!--errors-->
  <% if @user && @user.errors.any? %>
      <div class="alert alert-danger">
        <% @user.errors.full_messages.each do |error| %>
            <p><%= error %></p>
        <% end %>
      </div>
  <% end %>

  <!--form-->
  <%= form_for :user, class: 'form form-horizontal', url: signup_path(@user), method: :post do |f| %>

      <!--name-->
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, placeholder: 'Enter your name', class: 'form-control' %>
      </div>

      <!--email-->
      <div class="form-group">
        <%= f.label :email %>
        <%= f.text_field :email, placeholder: 'Enter your email', class: 'form-control' %>
      </div>

      <!--email confirmation-->
      <div class="form-group">
        <%= f.label :email_confirmation %>
        <%= f.text_field :email_confirmation, placeholder: 'Re-enter your email', class: 'form-control' %>
      </div>

      <!--password-->
      <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, placeholder: 'Enter a password', class: 'form-control' %>
      </div>

      <!--address-->
      <div class="form-group">
        <%= f.label :address %>
        <%= f.text_field :address, placeholder: 'Enter your address', class: 'form-control' %>
      </div>

      <!--submit-->
      <div class="form-group">
        <%= f.submit 'Save', class: 'btn btn-primary' %>
      </div>

  <% end %>

</div>

app/views/welcome/index.html.erb
<div class="container">
  <h1>Ruby on Rails Assignment - Group 123</h1>

  <p>This is our new blog!</p>

  <p>We managed to implement the following:</p>
  <ul>
    <li>User registration</li>
    <li>Profile view & edit</li>
    <li>Data validation</li>
  </ul>

  <p>You can find the code on L2P or on GitHub at this link:
    <a href="https://github.com/WebTech2-Group123/rails-assignment" target="_blank">https://github.com/WebTech2-Group123/rails-assignment</a>
  </p>
</div>